version: "3"

services:

  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
    - "5432:5432"
    volumes:
    - ./tests/data/postgres:/var/lib/postgresql/data

  initdb:
    build:
      dockerfile: ./Dockerfile.test-airflow
      context: .
    command: db init
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres/airflow
    depends_on:
      - postgres

  webserver:
    build:
      dockerfile: ./Dockerfile.test-airflow
      context: .
    command: webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres/airflow
      - AIRFLOW__SCHEDULER__STATSD_ON=True
      - AIRFLOW__SCHEDULER__STATSD_HOST=statsd-exporter
      - AIRFLOW__SCHEDULER__STATSD_PORT=8125
      - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
    ports:
      - "8080:8080"
    depends_on:
      - initdb
      - postgres
    volumes:
      - ./tests/dags:/opt/airflow/dags
#      - ./airflow/plugins:/opt/airflow/plugins
#      - ./tests/logs:/opt/airflow/logs

  scheduler:
    build:
      dockerfile: ./Dockerfile.test-airflow
      context: .
    command: scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres/airflow
      - AIRFLOW__SCHEDULER__STATSD_ON=True
      - AIRFLOW__SCHEDULER__STATSD_HOST=statsd-exporter
      - AIRFLOW__SCHEDULER__STATSD_PORT=8125
      - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
    depends_on:
      - initdb
      - postgres
    volumes:
      - ./tests/dags:/opt/airflow/dags
#      - ./airflow/plugins:/opt/airflow/plugins
#      - ./tests/logs:/opt/airflow/logs
  statsd-exporter:
    image: prom/statsd-exporter
    container_name: airflow-statsd-exporter
    command: "--statsd.listen-udp=:8125 --statsd.listen-tcp=:8125 --web.listen-address=:9102"
    ports:
      - 9123:9102
      - 8125:8125/udp
      - 8125:8125/tcp
